name: Run Stream Probe

on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pyyaml

      - name: Run stream probe
        run: |
          python3 max_info.py -c stream_probe.yml